---
- name: Install Python3 Pip
  become: yes
  apt:
    name: "{{ python_packages }}"
    state: present
    update_cache: yes
  with_items: "{{ python_packages }}"

- name: Install AWS CLI
  become: yes
  pip:
    name: awscli
    state: present

- name: Set home directory of the user
  set_fact:
    home_dir: /home/{{ aws_cli_user }}
  when: "not aws_cli_user == 'root'"

- name: Set home directory for root
  set_fact:
    home_dir: /root
  when: "aws_cli_user == 'root'"

- name: Create AWS config directory
  become: yes
  file:
    path: "{{ home_dir }}/.aws"
    state: directory
    owner: "{{ aws_cli_user }}"

- name: Copy AWS CLI config
  become: yes
  template:
    src: aws_cli_config.j2
    dest: "{{ home_dir }}/.aws/config"
    mode: 0600
    owner: "{{ aws_cli_user }}"

- name: Copy AWS CLI credentials
  become: yes
  template:
    src: aws_cli_credentials.j2
    dest: "{{ home_dir }}/.aws/credentials"
    mode: 0600
    owner: "{{ aws_cli_user }}"