- name: Install unzip
  become: yes
  apt:
    pkg: unzip
    state: present

- name: Install Terraform
  become: yes
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip
    dest: /usr/bin
    remote_src: yes